name: Pre-Commit checks

on:
  push:
    branches: [ master,  pre-commit-ci ]
  pull_request:
    branches: [ master ]

jobs:

  pre-commit:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Senz App
        uses: actions/checkout@master
        with:
          repository: lameland/senz

      - name: Checkout Python3
        uses: actions/setup-python@v2

      - name: Install requirements for tests
        run: python -m pip install flake8

      - name: Check code with flake8
        run: flake8 app/*.py */*.py